after(),
all(),
allowing(),
ancestor(),
ancestor-or-self(),
and(),
andAlso(),
any(),
array(),
(: array-node(), (: Reserved Function Name - MarkLogic 8.0 :) :)
as(),
ascending(),
assignable(),
at(),
(: attribute(), (: Reserved Function Name - XPath 2.0 and XQuery 1.0 :) :)
(: attribute-decl(), (: Reserved Function Name - MarkLogic 7.0 :) :)
base-uri(),
before(),
(: binary(), (: Reserved Function Name - MarkLogic 6.0 :) :)
block(),
(: boolean-node(), (: Reserved Function Name - MarkLogic 8.0 :) :)
boundary-space(),
by(),
case(),
cast(),
castable(),
catch(),
child(),
collation(),
(: comment(), (: Reserved Function Name - XPath 1.0 and XQuery 1.0 :) :)
(: complex-type(), (: Reserved Function Name - MarkLogic 7.0 :) :)
construction(),
contains(),
content(),
context(),
copy(),
copy-namespaces(),
count(),
decimal-format(),
decimal-separator(),
declare(),
default(),
delete(),
descendant(),
descendant-or-self(),
descending(),
diacritics(),
different(),
digit(),
distance(),
div(),
document(),
(: document-node(), (: Reserved Function Name - XPath 2.0 and XQuery 1.0 :) :)
(: element(), (: Reserved Function Name - XPath 2.0 and XQuery 1.0 :) :)
(: element-decl(), (: Reserved Function Name - MarkLogic 7.0 :) :)
else(),
(: empty(), (: Reserved Function Name - XPath 2.0 WD 2003 and XQuery 1.0 WD 2003 :) :)
(: empty-sequence(), (: Reserved Function Name - XPath 2.0 and XQuery 1.0 :) :)
encoding(),
end(),
entire(),
eq(),
every(),
exactly(),
except(),
exit(),
exponent-separator(),
external(),
first(),
fn(),
following(),
following-sibling(),
for(),
from(),
ft-option(),
ftand(),
ftnot(),
ftor(),
(: function(), (: Reserved Function Name - XPath 3.0 and XQuery 3.0 :) :)
fuzzy(),
ge(),
greatest(),
group(),
grouping-separator(),
gt(),
idiv(),
(: if(), (: Reserved Function Name - XPath 2.0 and XQuery 1.0 :) :)
import(),
in(),
infinity(),
inherit(),
insensitive(),
insert(),
instance(),
intersect(),
into(),
invoke(),
is(),
(: item(), (: Reserved Function Name - XPath 2.0 and XQuery 1.0 :) :)
language(),
last(),
lax(),
le(),
least(),
let(),
levels(),
lowercase(),
lt(),
map(),
minus-sign(),
mod(),
modify(),
module(),
most(),
namespace(),
(: namespace-node(), (: Reserved Function Name - XPath 3.0 and XQuery 3.0 :) :)
NaN(),
ne(),
next(),
no(),
no-inherit(),
no-preserve(),
(: node(), (: Reserved Function Name - XPath 1.0 and XQuery 1.0 :) :)
nodes(),
non-deterministic(),
not(),
(: null-node(), (: Reserved Function Name - MarkLogic 8.0 :) :)
(: number-node(), (: Reserved Function Name - MarkLogic 8.0 :) :)
(: object-node(), (: Reserved Function Name - MarkLogic 8.0 :) :)
occurs(),
of(),
only(),
option(),
or(),
order(),
ordered(),
ordering(),
orElse(),
paragraph(),
paragraphs(),
parent(),
pattern-separator(),
per-mille(),
percent(),
phrase(),
preceding(),
preceding-sibling(),
preserve(),
previous(),
private(),
(: processing-instruction(), (: Reserved Function Name - XPath 1.0 and XQuery 1.0 :) :)
property(),
public(),
relationship(),
rename(),
replace(),
return(),
returning(),
revalidation(),
same(),
satisfies(),
schema(),
(: schema-attribute(), (: Reserved Function Name - XPath 2.0 and XQuery 1.0 :) :)
(: schema-component(), (: Reserved Function Name - MarkLogic 7.0 :) :)
(: schema-element(), (: Reserved Function Name - XPath 2.0 and XQuery 1.0 :) :)
(: schema-facet(), (: Reserved Function Name - MarkLogic 8.0 :) :)
(: schema-particle(), (: Reserved Function Name - MarkLogic 7.0 :) :)
(: schema-root(), (: Reserved Function Name - MarkLogic 7.0 :) :)
(: schema-type(), (: Reserved Function Name - MarkLogic 7.0 :) :)
score(),
self(),
sensitive(),
sentence(),
sentences(),
sequential(),
simple(),
(: simple-type(), (: Reserved Function Name - MarkLogic 7.0 :) :)
skip(),
sliding(),
some(),
stable(),
start(),
stemming(),
stop(),
strict(),
strip(),
sliding(),
stable(),
start(),
stemming(),
stop(),
strict(),
strip(),
stylesheet(),
(: switch(), (: Reserved Function Name - XPath 3.0 and XQuery 3.0 :) :)
(: text(), (: Reserved Function Name - XPath 1.0 and XQuery 1.0 :) :)
then(),
thesaurus(),
times(),
to(),
transform(),
treat(),
try(),
tumbling(),
tuple(),
type(),
(: typeswitch(), (: Reserved Function Name - XPath 2.0 and XQuery 1.0 :) :)
unassignable(),
union(),
unordered(),
update(),
updating(),
uppercase(),
using(),
validate(),
value(),
variable(),
version(),
weight(),
when(),
where(),
(: while(), (: Reserved Function Name - XQuery 1.0 Scripting Extension :) :)
wildcards(),
window(),
with(),
without(),
word(),
words(),
xquery(),
zero-digit()