allowing() ,
catch() ,
context() ,
count() ,
decimal-format() ,
decimal-separator() ,
digit() ,
end() ,
group() ,
grouping-separator() ,
infinity() ,
minus-sign() ,
(: Reserved Function Name -- namespace-node :)
NaN() ,
next() ,
only() ,
pattern-separator() ,
per-mille() ,
percent() ,
previous() ,
sliding() ,
start() ,
(: Reserved Function Name -- switch :)
try() ,
tumbling() ,
type() ,
when() ,
window() ,
zero-digit()
