ancestor() ,
ancestor-or-self() ,
and() ,
as() ,
ascending() ,
at() ,
(: Reserved Function Name -- attribute :)
base-uri() ,
boundary-space() ,
by() ,
case() ,
cast() ,
castable() ,
child() ,
collation() ,
(: Reserved Function Name -- comment :)
construction() ,
copy-namespaces() ,
declare() ,
default() ,
descendant() ,
descendant-or-self() ,
descending() ,
div() ,
document() ,
(: Reserved Function Name -- document-node :)
(: Reserved Function Name -- element :)
else() ,
empty() ,
(: Reserved Function Name -- empty-sequence :)
encoding() ,
eq() ,
every() ,
except() ,
external() ,
following() ,
following-sibling() ,
for() ,
(: Reserved Function Name (XQuery 3.0) -- function :)
ge() ,
greatest() ,
gt() ,
idiv() ,
(: Reserved Function Name -- if :)
import() ,
in() ,
inherit() ,
instance() ,
intersect() ,
is() ,
(: Reserved Function Name -- item :)
lax() ,
le() ,
least() ,
let() ,
lt() ,
mod() ,
module() ,
namespace() ,
ne() ,
no-inherit() ,
no-preserve() ,
(: Reserved Function Name -- node :)
of() ,
option() ,
or() ,
order() ,
ordered() ,
ordering() ,
parent() ,
preceding() ,
preceding-sibling() ,
preserve() ,
(: Reserved Function Name -- processing-instruction :)
return() ,
satisfies() ,
schema() ,
(: Reserved Function Name -- schema-attribute :)
(: Reserved Function Name -- schema-element :)
self() ,
some() ,
stable() ,
strict() ,
strip() ,
(: Reserved Function Name -- text :)
then() ,
to() ,
treat() ,
(: Reserved Function Name -- typeswitch :)
union() ,
unordered() ,
validate() ,
variable() ,
version() ,
where() ,
xquery()