declare option test "Test Case" ;
declare base-uri "http://www.example.org" ;
declare boundary-space strip ;
declare construction strip ;
declare copy-namespaces preserve , inherit ;
declare default collation "http://www.example.org/lang/es" ;
declare default element namespace "http://www.example.org/test" ;
declare default order empty greatest ;
declare namespace test = "http://www.example.org/test" ;
declare ordering ordered ;
import module "http://www.example.com/test" ;
import schema "http://www.example.com/test" ;